# fly.toml file generated for web-mentor on 2022-10-03T02:21:39Z

app = "web-mentor"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  MONGO_URI = "mongodb+srv://hellogit:9FngQBmdoW0BUaod@cluster0.mkxwi.mongodb.net/grading?retryWrites=true&w=majority"
  SECRET_KEY = "be189a3a7ba4267df5606eb22decf39c9a1deb0b78cf475b6e16a1d19799de037045653ab8dd5788243a981c0aa1063186eb208aeae4c93f83c2e7676dd00353"
  CLIENT_ID = "534065423825-cnrgec2r6e33kkmoutetjggl7gst8vvs.apps.googleusercontent.com"
  CLIENT_SECRET = "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"
  REDIRECT_URI = "https://developers.google.com/oauthplayground"
  REFRESH_TOKEN_GMAIL = "1//04Im0_LGG2EX8CgYIARAAGAQSNwF-L9Irj21LK1jb--7d-qNUFurCGUKZbMKFSxMaiLlUGdH0X7_mFZd6CSnpHPySYAYp_bJN_YU"
  CLOUDINARY_CLOUD_NAME = "dpqr3x0ac"
  CLOUDINARY_API_KEY = "416522749777139"
  CLOUDINARY_API_SECRET = "Y2EjqPNEVGjSNbZfYTzaWx27tPQ"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"