import { check } from 'express-validator';
import { messageVietnamese } from '../../../utils/message';

//? CREATE MENTOR ACCOUNT
export const mentorSchema = [
    check('username')
      .not()
      .isEmpty()
      .withMessage(messageVietnamese.ER001())
      .bail()
    check('password')
      .not()
      .isEmpty()
      .withMessage()
      .bail()
    check('cPassword')
      .not()
      .isEmpty()
      .withMessage()
      .bail()
    check('email')
      .not()
      .isEmpty()
      .withMessage()
      .bail()
    check('campus')
      .not()
      .isEmpty()
      .withMessage()
      .bail()
]
  
  //? CREATE LEADER ACCOUNT
export const leaderSchema = [
    check('username')
      .not()
      .isEmpty()
      .withMessage()
      .bail()
    check('password')
      .not()
      .isEmpty()
      .withMessage()
      .bail()
    check('cPassword')
      .not()
      .isEmpty()
      .withMessage()
      .bail()
    check('email')
      .not()
      .isEmpty()
      .withMessage()
      .bail()
    check('campus')
      .not()
      .isEmpty()
      .withMessage()
      .bail()
    check('club')
      .not()
      .isEmpty()
      .withMessage()
      .bail()
  ]
  